/*
# GemWale E-Commerce Schema

## Overview
Creates the full database for the GemWale gemstone jewellery store: categories,
collections, products, customers, orders, and order items. This is a single-tenant
no-auth storefront (customers checkout via WhatsApp, admin manages via dashboard),
so all policies are open to anon + authenticated.

## New Tables
1. `categories` — product categories (Necklaces, Pendants, Bracelets, Rings, Malas, Earrings, Keychains)
   - id, name, slug, description, image_url, display_order, created_at
2. `collections` — curated collections (New Arrivals, Best Sellers, Trending Now, Featured Edit, Latest Drops, Fresh Styles, Signature Pieces, Limited Edition, Top Picks, Unisex)
   - id, name, slug, tagline, description, image_url, display_order, created_at
3. `products` — the jewellery catalogue
   - id, name, slug, product_code, price, category_id, collection_id, colour, colours (text[]), images (text[]), description, details, care_instructions, stock, availability, is_featured, is_bestseller, is_trending, is_new_arrival, is_limited_edition, is_unisex, display_order, created_at
4. `customers` — customer delivery details captured at checkout
   - id, full_name, phone, email, address, city, state, pin_code, country, created_at
5. `orders` — order header
   - id, order_id (unique GW-YYYY-NNNNN), customer_id, total, order_status, payment_status, created_at
6. `order_items` — line items per order
   - id, order_id, product_id, product_code, product_name, colour, quantity, price

## Security
- RLS enabled on every table.
- All tables allow anon + authenticated full CRUD (single-tenant, no-auth storefront).
  The storefront must write customer/order rows as the anon-key client.

## Notes
1. Order statuses: WhatsApp Contacted, Payment Pending, Payment Received, Processing, Shipped, Delivered, Cancelled.
2. Payment statuses: Pending, Paid, Failed, Refunded.
3. `order_id` is a unique human-readable code generated by the app (GW-2026-00001).
4. Product `colours` is a text array so a single product can be offered in multiple colour options.
*/

CREATE TABLE IF NOT EXISTS categories (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text UNIQUE NOT NULL,
  description text,
  image_url text,
  display_order int NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS collections (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text UNIQUE NOT NULL,
  tagline text,
  description text,
  image_url text,
  display_order int NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text UNIQUE NOT NULL,
  product_code text NOT NULL,
  price numeric(10,2) NOT NULL,
  category_id uuid REFERENCES categories(id) ON DELETE SET NULL,
  collection_id uuid REFERENCES collections(id) ON DELETE SET NULL,
  colour text,
  colours text[] DEFAULT '{}',
  images text[] DEFAULT '{}',
  description text,
  details text,
  care_instructions text,
  stock int NOT NULL DEFAULT 0,
  availability text DEFAULT 'In Stock',
  is_featured boolean NOT NULL DEFAULT false,
  is_bestseller boolean NOT NULL DEFAULT false,
  is_trending boolean NOT NULL DEFAULT false,
  is_new_arrival boolean NOT NULL DEFAULT false,
  is_limited_edition boolean NOT NULL DEFAULT false,
  is_unisex boolean NOT NULL DEFAULT false,
  display_order int NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS customers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name text NOT NULL,
  phone text NOT NULL,
  email text,
  address text NOT NULL,
  city text NOT NULL,
  state text NOT NULL,
  pin_code text NOT NULL,
  country text NOT NULL DEFAULT 'India',
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id text UNIQUE NOT NULL,
  customer_id uuid REFERENCES customers(id) ON DELETE SET NULL,
  total numeric(10,2) NOT NULL,
  order_status text NOT NULL DEFAULT 'WhatsApp Contacted',
  payment_status text NOT NULL DEFAULT 'Pending',
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS order_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id uuid REFERENCES orders(id) ON DELETE CASCADE,
  product_id uuid REFERENCES products(id) ON DELETE SET NULL,
  product_code text NOT NULL,
  product_name text NOT NULL,
  colour text,
  quantity int NOT NULL DEFAULT 1,
  price numeric(10,2) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_collection ON products(collection_id);
CREATE INDEX IF NOT EXISTS idx_products_slug ON products(slug);
CREATE INDEX IF NOT EXISTS idx_orders_order_id ON orders(order_id);
CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items(order_id);

ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_crud_categories" ON categories;
CREATE POLICY "anon_crud_categories" ON categories FOR ALL
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_crud_collections" ON collections;
CREATE POLICY "anon_crud_collections" ON collections FOR ALL
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_crud_products" ON products;
CREATE POLICY "anon_crud_products" ON products FOR ALL
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_crud_customers" ON customers;
CREATE POLICY "anon_crud_customers" ON customers FOR ALL
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_crud_orders" ON orders;
CREATE POLICY "anon_crud_orders" ON orders FOR ALL
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_crud_order_items" ON order_items;
CREATE POLICY "anon_crud_order_items" ON order_items FOR ALL
  TO anon, authenticated USING (true) WITH CHECK (true);
